### ISSUE TITLE
Please create a stable release

### ISSUE THREAD

**Issue by MrPetovan** [sarahman/simple-filesystem-cache#1]
Hi, I'm interested in this library, can you please publish a release named `1.0` through GitHub?

Doing this:
- Creates a tag named `1.0` on the current commit.
- Allows Composer to find a stable version for this package.

Thanks!

**Comment by sarahman** [comment]
Thanks for encouraging me.

A [stable version](https://github.com/sarahman/simple-filesystem-cache/releases/tag/v1.0.0) has been released.

**Comment by MrPetovan** [comment]
You're welcome, and thank you!

**Comment by MrPetovan** [comment]
Thanks, our project [friendica/friendica-directory](https://github.com/friendica/friendica-directory/releases/tag/v2.2.1) is now using the `v1.0` of `sarahman/simple-filesystem-cache`!
